---
- name: "Get facts of all RKE nodes"

  hosts: rke_node:!type_openstack_compute_floatingip_associate_v2
  become: yes
  become_user: root

  tasks:
    - name: Grab OpenStack metadata
      uri:
        url: http://169.254.169.254/openstack/2012-08-10/meta_data.json
        body_format: json
      register: metadata
    # Using 'ansible_hostname' would work as well, but just to be sure,
    # lets use the same source that kubelet will
    # See: https://github.com/kubernetes/kubernetes/commit/6ab76041b7845af6de51752434e317b52e6ba24c
    - name: Set os_metadata_name and os_metadata_hostname facts
      set_fact:
        os_metadata_hostname: "{{ metadata['json']['hostname'] }}"
        os_metadata_name: "{{ metadata['json']['name'] }}"

- name: "Install RKE"

  hosts: controller:!type_openstack_compute_floatingip_associate_v2
  become: yes
  become_user: root

  vars:
    RKE_VERSION: "0.1.8"

  handlers:
    - name: restart_nginx
      service:
        daemon_reload: yes
        name: nginx
        state: restarted
        enabled: yes

  tasks:
    - name: Ensure /opt/bin exists
      file:
        path: /opt/bin
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Add /opt/bin to PATH for all users
      copy:
        dest: /etc/profile.d/opt-bin.sh
        content: |
          export PATH=$PATH:/opt/bin
    - name: Download RKE
      get_url:
        url: "https://github.com/rancher/rke/releases/download/v{{ RKE_VERSION }}/rke_linux-amd64"
        dest: /opt/bin/rke
        owner: root
        group: root
        mode: 0755

    - name: Copy SSH key
      copy:
        src: ~/.ssh/candig_dev_key_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0600
    - name: Copy cluster.yml
      template:
        src: cluster.j2.yml
        dest: /home/ubuntu/cluster.yml
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Add google cloud key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Add kubernetes apt repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes.list
    - name: Install kubectl
      apt:
        name: "{{ item }}"
      with_items:
        - kubectl

    - name: Add Ansible apt repository
      apt_repository:
        repo: ppa:ansible/ansible
    - name: Install Ansible
      apt: name=ansible update_cache=yes
    - name: Copy hosts
      copy:
        src: ./hosts
        dest: /home/ubuntu/hosts
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Copy snapshot.yml
      copy:
        src: ./snapshot.yml
        dest: /home/ubuntu/snapshot.yml
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Copy restore.yml
      copy:
        src: ./restore.yml
        dest: /home/ubuntu/restore.yml
        owner: ubuntu
        group: ubuntu
        mode: 0644
