version: '3.3'

services:
  minio:
    image: minio/minio:RELEASE.2018-08-02T23-11-36Z
    volumes:
      - "/data:/data"
    ports:
      - "9000:9000"
    command: server /data
    secrets:
      - source: minio_access_key
        target: access_key
      - source: minio_secret_key
        target: secret_key
    restart: 'no'

secrets:
  minio_access_key:
    file: ./secrets/minio_access_key
  minio_secret_key:
    file: ./secrets/minio_secret_key
