---
- name: CoreDNS with etcd backend

  hosts: coredns
  become: yes

  handlers:
    - name: restart_coredns
      service:
        daemon_reload: yes
        name: coredns
        state: restarted
        enabled: yes

  tasks:
    - name: Ensure /etc/cfssl exists
      file:
        path: /etc/cfssl
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Copy ca.pem
      copy:
        src: ./pkitest_ca.pem
        dest: /etc/cfssl/ca.pem
        owner: root
        group: root
        mode: 0644
    - name: Copy request-profile.json
      template:
        src: ./request-profile.json
        dest: /etc/cfssl/request-profile.json
        owner: root
        group: root
        mode: 0644
    - name: Copy etcd-coredns.csr.json
      copy:
        src: ./etcd-coredns.csr.json
        dest: /etc/cfssl/etcd-coredns.csr.json
        owner: root
        group: root
        mode: 0644
    - name: Generate root user client TLS cert
      shell: >
        docker run --rm -v /etc/cfssl:/etc/ssl -w /etc/ssl --entrypoint /usr/bin/env cfssl/cfssl:1.3.2 sh -c "
        cfssl gencert
        -config=request-profile.json
        -tls-remote-ca ca.pem
        -profile=client
        etcd-coredns.csr.json |
        cfssljson -bare etcd-coredns
        "
      args:
        creates: /etc/cfssl/etcd-coredns.pem


    - name: Ensure /opt/coredns exists
      file:
        path: /opt/coredns
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /opt/coredns/docker-compose.yml
        owner: root
        group: root
        mode: 0644
      notify: restart_coredns
    - name: Copy systemd unit
      copy:
        src: ./coredns.service
        dest: /etc/systemd/system/coredns.service
        owner: root
        group: root
        mode: 0644

    - name: Ensure /etc/coredns exists
      file:
        path: /etc/coredns
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Copy Corefile
      copy:
        src: ./Corefile
        dest: /etc/coredns/Corefile
        owner: root
        group: root
        mode: 0644
      notify: restart_coredns

    - name: Start coredns service
      service:
        daemon_reload: yes
        name: coredns
        state: started
        enabled: yes
